#lang racket
(require "../sexp-edit.rkt" "../helper-algebras.rkt")
(define index-of (make-lens (lambda (g) (values (guide-index g) slot-guide))))
(define (each* fl fr) (updater (vref 0 1) (lambda (gs) (map (lambda (g f) ((updater index-of f) g))
                                                            gs (list fl fr)))))
(define (both* f) (each* f f))
(define (foc z) (~a ((viewer zipper-focus) z)))
(define rope ((make-rope sexp-smr) "(aa bb cc)"))
(define z  (cursor rope '(1 0)))
(define z2 (cursor rope '(1 0) '(2 0)))
(printf "each* ~s expect \"bb \"\n" (foc ((updater zipper-guide (each* values (slot add1))) z)))
(printf "both* ~s expect \"cc\"\n"  (foc ((updater zipper-guide (both* (slot add1))) z2)))
